### ISSUE TITLE
High Quality Ambient Light broken 

### ISSUE THREAD

**Issue by Ultra119** [X0nk/Bliss-Shader#223]
High Quality Ambient Light crashing after 7607c0ff412c2b20412c26a7d9f6fd1c8434c15b commit

```
[16:40:25] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
net.irisshaders.iris.gl.shader.ShaderCompileException: composite2.fsh: composite2.fsh: ERROR: 0:906: 'minLightColor' : undeclared identifier 
ERROR: 0:906: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.


	at net.irisshaders.iris.gl.shader.GlShader.createShader(GlShader.java:46) ~[iris-1.7.1+mc1.21.jar:?]
	at net.irisshaders.iris.gl.shader.GlShader.<init>(GlShader.java:25) ~[iris-1.7.1+mc1.21.jar:?]
	at net.irisshaders.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:88) ~[iris-1.7.1+mc1.21.jar:?]
	at net.irisshaders.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[iris-1.7.1+mc1.21.jar:?]
	at net.irisshaders.iris.pipeline.CompositeRenderer.createProgram(CompositeRenderer.java:326) ~[iris-1.7.1+mc1.21.jar:?]
	at net.irisshaders.iris.pipeline.CompositeRenderer.<init>(CompositeRenderer.java:123) ~[iris-1.7.1+mc1.21.jar:?]
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.<init>(IrisRenderingPipeline.java:321) ~[iris-1.7.1+mc1.21.jar:?]
	at net.irisshaders.iris.Iris.createPipeline(Iris.java:578) ~[iris-1.7.1+mc1.21.jar:?]
	at net.irisshaders.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:33) ~[iris-1.7.1+mc1.21.jar:?]
	at net.irisshaders.iris.Iris.reload(Iris.java:529) ~[iris-1.7.1+mc1.21.jar:?]
	at net.irisshaders.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[iris-1.7.1+mc1.21.jar:?]
	at net.irisshaders.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:624) ~[iris-1.7.1+mc1.21.jar:?]
	at net.irisshaders.iris.gui.screen.ShaderPackScreen.lambda$init$6(ShaderPackScreen.java:265) ~[iris-1.7.1+mc1.21.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.irisshaders.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:226) ~[iris-1.7.1+mc1.21.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.3.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) [lwjgl-glfw-3.3.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150) [client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168) [client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:303) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1307) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]

```

**Comment by X0nk** [comment]
fixed, go redownload
