### ISSUE TITLE
Game crashes with DH

### ISSUE THREAD

**Issue by kevinthmm** [X0nk/Bliss-Shader#348]
### Describe the bug
Describe the bug in as much detail as possible. capturing footage of it with images or videos is preferred.

Hi there! First of all, thank you so much for creating this shader I honestly think its one of the best shaders amongst all the other's over seen over time! However I unfortunately have been getting game crashes on world load. The console. log output is as the following: 
`
23:31:43.745
net.irisshaders.iris.gl.shader.ProgramCreator
Render thread
Program link log for composite2: WARNING: Could not find vertex shader attribute 'at_tangent' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'mc_midTexCoord' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'UV0' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'iris_Entity' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'at_midBlock' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'mc_Entity' to match BindAttributeLocation request.
WARNING: Output of vertex shader 'zMults' not read by fragment shader
WARNING: Output of vertex shader 'iris_FogFragCoord' not read by fragment shader
23:31:43.747
Iris
Render thread
Failed to create shader rendering pipeline, disabling shaders!
java.lang.IllegalStateException: No more available texture units while activating sampler depthtex0
	at knot//net.irisshaders.iris.gl.program.ProgramSamplers$Builder.addDynamicSampler(ProgramSamplers.java:198)
	at knot//net.irisshaders.iris.gl.program.ProgramSamplers$Builder.addDynamicSampler(ProgramSamplers.java:170)
	at knot//net.irisshaders.iris.gl.sampler.SamplerHolder.addDynamicSampler(SamplerHolder.java:28)
	at knot//net.irisshaders.iris.gl.program.ProgramBuilder.addDynamicSampler(ProgramBuilder.java:130)
	at knot//net.irisshaders.iris.gl.program.ProgramSamplers$CustomTextureSamplerInterceptor.addDynamicSampler(ProgramSamplers.java:303)
	at knot//net.irisshaders.iris.samplers.IrisSamplers.addCompositeSamplers(IrisSamplers.java:212)
	at knot//net.irisshaders.iris.pipeline.CompositeRenderer.createProgram(CompositeRenderer.java:381)
	at knot//net.irisshaders.iris.pipeline.CompositeRenderer.<init>(CompositeRenderer.java:127)
	at knot//net.irisshaders.iris.pipeline.IrisRenderingPipeline.<init>(IrisRenderingPipeline.java:334)
	at knot//net.irisshaders.iris.Iris.createPipeline(Iris.java:616)
	at knot//net.irisshaders.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:33)
	at knot//net.irisshaders.iris.Iris.onLoadingComplete(Iris.java:150)
	at knot//net.minecraft.class_442.handler$zif000$iris$firstInit(class_442.java:525)
	at knot//net.minecraft.class_442.method_25426(class_442.java:143)
	at knot//net.minecraft.class_437.method_25423(class_437.java:309)
	at knot//net.minecraft.class_310.method_1507(class_310.java:1143)
	at knot//net.minecraft.class_310.method_53528(class_310.java:737)
	at knot//net.minecraft.class_310.redirect$zzj000$distanthorizons$buildInitialScreens(class_310.java:3257)
	at knot//net.minecraft.class_310.method_51736(class_310.java:722)
	at knot//net.minecraft.class_310.method_53465(class_310.java:711)
	at knot//net.minecraft.class_310.method_29338(class_310.java:701)
	at knot//net.minecraft.class_156.method_17974(class_156.java:597)
	at knot//net.minecraft.class_310.method_53522(class_310.java:696)
	at knot//net.minecraft.class_425.method_25394(class_425.java:149)
	at knot//net.minecraft.class_757.method_3192(class_757.java:902)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
23:31:53.905
Iris
Render thread
Destroying pipeline minecraft:overworld
23:31:53.906
Iris
Render thread
Shaders are disabled because enableShaders is set to false in iris.properties
23:31:55.913
net.minecraft.class_310
Render thread
Stopping!
23:31:55.942
class_757
Render thread
Shutting down renderer (fabric)
`

### Describe how your minecraft is set up
1. Include a screenshot of the in-game f3 debug overlay. Please make sure it is fully visible.

2. If you cannot do option 1. Please list the following information instead:
- Apple M1 Max (10 Core CPU / 24 Core GPU / 32 GB Ram, allocated 16 GB to MC)
- macOS 15.1 (24B83) Sequoia 
- 1.21.1
- Stock vanilla client
- Iris + Fabric + Sodium
- Bliss Shader Main
- DistantHorizons-2.2.1-a-1.21.1-neo-fabric

### Describe how to reproduce the bug
Show exactly how to make the bug appear, if you can. Video footage is preferred.

- In single player creating a creative normal world. 
- DH works without bliss shader
- Bliss shader works without DH
- Bliss shader + DH = Crash =( 

if it is happening on content from a mod, list what mod, and what content of that mod it happens on.
-
if a specific shader setting can make it start/stop bugging, please list what shader setting does that.

<img width="1802" alt="Screenshot 2024-11-22 at 12 35 28 PM" src="https://github.com/user-attachments/assets/67bbec3f-f165-44ff-9ba0-0d1b2aaf7e0f">

-

**Comment by X0nk** [comment]
i have some unfortunate news, apple devices + bliss + DH cannot work. 
[read here for more info about that](https://github.com/X0nk/Bliss-Shader/issues/181)

use a different shader. i know that [complementary](https://modrinth.com/shader/complementary-reimagined) or [BSL](https://modrinth.com/shader/bsl-shaders) will work on apple devices with distant horizons. but those arent the only ones out there.

**Comment by kevinthmm** [comment]
damn thats unfortunate =( thanks for your hard work nevertheless! Ill give complementary a shot
