### ISSUE TITLE
Broken sky sometimes on shader reload with distant horizons

### ISSUE THREAD

**Issue by Pleune** [X0nk/Bliss-Shader#58]
It's very random when it will happen, but here is my log. Using the latest code

![2024-03-07_21 12 42](https://github.com/X0nk/Bliss-Shader/assets/9004509/599668e2-fcb1-4ae3-b966-25346f204daa)

<details>
> [21:12:32] [Render thread/INFO]: Destroying pipeline NamespacedId{namespace='minecraft', name='overworld'}
[21:12:32] [Render thread/WARN]: Ignoring ambiguous boolean option WEATHER
[21:12:32] [Render thread/WARN]: Ignoring ambiguous boolean option LIGHTSOURCE_REFLECTION
[21:12:32] [Render thread/WARN]: Ignoring ambiguous boolean option LIGHTSOURCE_REFLECTION
[21:12:32] [Render thread/WARN]: Ignoring ambiguous boolean option WORLD
[21:12:32] [Render thread/WARN]: Ignoring ambiguous boolean option WORLD
[21:12:32] [Render thread/ERROR]: Invalid alpha test directive for gbuffers_hand: true
[21:12:32] [Render thread/WARN]: Tried to get boolean value for unknown option: , defaulting to true!
[21:12:32] [Render thread/WARN]: Tried to get boolean value for unknown option: , defaulting to true!
[21:12:32] [Render thread/WARN]: Unable to resolve shader pack option menu element "HEIGTHMAP_DEPTH_OFFSET" defined in shaders.properties
[21:12:32] [Render thread/WARN]: Unable to resolve shader pack option menu element "<EMPTY>" defined in shaders.properties
[21:12:32] [Render thread/WARN]: Unable to resolve shader pack option menu element "Compositing_Sky" defined in shaders.properties
[21:12:32] [Render thread/WARN]: Unable to resolve shader pack option menu element "AUTOFOCUS" defined in shaders.properties
[21:12:32] [Render thread/INFO]: Profile: Custom (+5 options changed by user)
[21:12:32] [Render thread/WARN]: Warning: the block ID map entry "conquest:conquest:iron_candelabrum_1" could not be fully parsed:
[21:12:32] [Render thread/WARN]: - Block state property filters must be of the form "key=value", but iron_candelabrum_1 is not of that form!
[21:12:32] [Render thread/WARN]: Warning: the block ID map entry "conquest:conquest:golden_candelabrum_1" could not be fully parsed:
[21:12:32] [Render thread/WARN]: - Block state property filters must be of the form "key=value", but golden_candelabrum_1 is not of that form!
[21:12:32] [Render thread/INFO]: Using shaderpack: Bliss-Shader-main.zip
[21:12:32] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[21:12:33] [Render thread/INFO]: Starting custom uniform resolving
[21:12:33] [Render thread/WARN]: Failed to resolve uniform dying, reason: Unknown variable: is_alive ( = FunctionCall{smooth {[FunctionCall{if {[UnaryExpr{not {Id{is_alive}} }, Number{2}, Number{0}]} }, Number{3}, Number{0}]} })
java.lang.RuntimeException: Unknown variable: is_alive
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:219) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpressionInternal(ExpressionResolver.java:73) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:104) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:182) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpressionInternal(ExpressionResolver.java:73) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:104) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:190) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpressionInternal(ExpressionResolver.java:73) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:104) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:190) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpression(ExpressionResolver.java:42) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:53) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:317) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:329) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:268) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:677) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:35) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:625) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at net.coderbot.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:586) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$3(ShaderPackScreen.java:244) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:198) ~[iris-mc1.20.1-1.7-alpha.1-185a9812.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1241) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[21:12:33] [Render thread/WARN]: The following uniforms won't work, either because they are broken, or reference a broken uniform: 
dead
[21:12:33] [Render thread/WARN]: The in declaration 'tempOffsets' in the FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[21:12:33] [Render thread/WARN]: [Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[21:12:33] [Render thread/WARN]: The in declaration 'exposure' in the FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[21:12:33] [Render thread/WARN]: Type is VERTEX
[21:12:33] [Render thread/WARN]: Type is FRAGMENT
[21:12:33] [Render thread/WARN]: Couldn't find worldYOffset
[21:12:33] [Render thread/WARN]: Couldn't find iris_ProjectionMatrixInverse
[21:12:33] [Render thread/WARN]: Couldn't find iris_ModelViewMatrixInverse
[21:12:33] [Render thread/WARN]: Couldn't find clipDistance
[21:12:33] [Render thread/WARN]: Type is VERTEX
[21:12:33] [Render thread/WARN]: Type is FRAGMENT
[21:12:33] [Render thread/WARN]: Couldn't find worldYOffset
[21:12:33] [Render thread/WARN]: Couldn't find iris_ProjectionMatrixInverse
[21:12:33] [Render thread/WARN]: Couldn't find iris_ModelViewMatrixInverse
[21:12:33] [Render thread/WARN]: Couldn't find iris_NormalMatrix
[21:12:33] [Render thread/WARN]: Couldn't find clipDistance
[21:12:33] [Render thread/INFO]: Stopping worker threads
[21:12:34] [Render thread/INFO]: Started 4 worker threads
[21:12:35] [Render thread/ERROR]: ########## GL ERROR ##########
[21:12:35] [Render thread/ERROR]: @ Render
[21:12:35] [Render thread/ERROR]: 65539: Invalid key -1
[21:12:35] [Render thread/ERROR]: ########## GL ERROR ##########
[21:12:35] [Render thread/ERROR]: @ Render
[21:12:35] [Render thread/ERROR]: 65539: Invalid key -1
[21:12:35] [Render thread/ERROR]: ########## GL ERROR ##########
[21:12:35] [Render thread/ERROR]: @ Render
[21:12:35] [Render thread/ERROR]: 65539: Invalid key -1
[21:12:35] [Render thread/ERROR]: ########## GL ERROR ##########
[21:12:35] [Render thread/ERROR]: @ Render
[21:12:35] [Render thread/ERROR]: 65539: Invalid key -1
[21:12:35] [Render thread/ERROR]: ########## GL ERROR ##########
[21:12:35] [Render thread/ERROR]: @ Render
[21:12:35] [Render thread/ERROR]: 65539: Invalid key -1
[21:12:35] [Render thread/ERROR]: ########## GL ERROR ##########
[21:12:35] [Render thread/ERROR]: @ Render
[21:12:35] [Render thread/ERROR]: 65539: Invalid key -1
[21:12:35] [Render thread/ERROR]: ########## GL ERROR ##########
[21:12:35] [Render thread/ERROR]: @ Render
[21:12:35] [Render thread/ERROR]: 65539: Invalid key -1
[21:12:35] [Render thread/ERROR]: ########## GL ERROR ##########
[21:12:35] [Render thread/ERROR]: @ Render
[21:12:35] [Render thread/ERROR]: 65539: Invalid key -1
[21:12:35] [Render thread/ERROR]: ########## GL ERROR ##########
[21:12:35] [Render thread/ERROR]: @ Render
[21:12:35] [Render thread/ERROR]: 65539: Invalid key -1
[21:12:35] [Render thread/ERROR]: ########## GL ERROR ##########
[21:12:35] [Render thread/ERROR]: @ Render
[21:12:35] [Render thread/ERROR]: 65539: Invalid key -1

</details>

**Comment by Pleune** [comment]
Seems like a DH / Iris issue instead, but other shaders clear the sky rather than the effect above for some reason

**Comment by Macintosh-Fan** [comment]
If I remember correctly, Distant Horizons can behave weirdly with shaders.

**Comment by X0nk** [comment]
if the sky does this it means distant horizons crashed, and you need to restart the game.

**Comment by EatingAvacadoToast** [comment]
I have the same issue but it has this problem on startup.

**Comment by X0nk** [comment]
there are 2 possible ways to stop this issue.
- restart the game this is usually just DH crashing. 
- if restarting does not fix it go to Distant horizons settings -> advanced options -> graphics -> rendering -> change transparency to complete

eventually this will be fixed on the iris test builds.
